name:                wys
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- mtl

library:
  source-dirs: src

executables:
  wys:
    main:                Main
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  wys-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wys
